# -*- coding: utf-8 -*-
"""AI Chatbot Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wt68bDRFm071mSO06jTsTHzuRwXXOHCa
"""

import json
import random
import pickle
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression

training_data = [
    ("I want to book a flight", "book_flight"),
    ("Book me a hotel", "book_hotel"),
    ("Cancel my booking", "cancel_booking"),
    ("I need to cancel flight", "cancel_booking"),
    ("What is the refund policy?", "faq"),
    ("How much luggage is allowed?", "faq"),
    ("Hello", "greeting"),
    ("Hi there", "greeting")
]

# Split into X, y
X_texts, y = zip(*training_data)

# Vectorize text
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X_texts)

# Train model
model = LogisticRegression()
model.fit(X, y)

# Save model + vectorizer
with open("chat_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Model trained and saved!")

